// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowMode() {
  return window['go']['main']['App']['GetWindowMode']();
}

export function SetWindowMode(arg1) {
  return window['go']['main']['App']['SetWindowMode'](arg1);
}
