// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowMode():Promise<string>;

export function SetWindowMode(arg1:string):Promise<void>;
