// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSyncServer() {
  return window['go']['main']['App']['ClearSyncServer']();
}

export function ResetStore() {
  return window['go']['main']['App']['ResetStore']();
}

export function GetWindowMode() {
  return window['go']['main']['App']['GetWindowMode']();
}

export function LoadSnapshot() {
  return window['go']['main']['App']['LoadSnapshot']();
}

export function SaveSnapshot(arg1) {
  return window['go']['main']['App']['SaveSnapshot'](arg1);
}

export function SetSyncServer(arg1, arg2) {
  return window['go']['main']['App']['SetSyncServer'](arg1, arg2);
}

export function SetWindowMode(arg1) {
  return window['go']['main']['App']['SetWindowMode'](arg1);
}

export function Sync() {
  return window['go']['main']['App']['Sync']();
}
